### ISSUE TITLE
im GEtting a Fatal Error When Lauching the App

### ISSUE THREAD

**Issue by Cumbemoz** [saifullah73/Nustana-Android#2]
08-26 11:54:31.381 2979-2979/com.cumbemoz.douradostakeaway E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NullPointerException
        at com.cumbemoz.douradostakeaway.MainActivity.setCurrentShopProfile(MainActivity.java:188)
        at com.cumbemoz.douradostakeaway.MainActivity.access$200(MainActivity.java:47)
        at com.cumbemoz.douradostakeaway.MainActivity$6.onDataChange(MainActivity.java:174)
        at com.google.firebase.database.zzp.onDataChange(Unknown Source)
        at com.google.android.gms.internal.firebase_database.zzfc.zza(Unknown Source)
        at com.google.android.gms.internal.firebase_database.zzgx.zzdr(Unknown Source)
        at com.google.android.gms.internal.firebase_database.zzhd.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:615)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4745)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by Nirmohi369** [comment]
i am unable to launch the app
